"""
setup.py — Interactive first-time configuration wizard.
Run this once to create your .env file with real API keys.

Usage:
    python setup.py
"""

import os
import sys
import requests

def test_football_api(key):
    url = "https://v3.football.api-sports.io/status"
    headers = {"x-apisports-key": key}
    try:
        r = requests.get(url, headers=headers, timeout=8)
        if r.status_code == 200:
            data = r.json().get("response", {})
            sub = data.get("subscription", {})
            requests_info = data.get("requests", {})
            plan = sub.get("plan", "Unknown")
            used = requests_info.get("current", "?")
            limit = requests_info.get("limit_day", "?")
            print(f"  ✅ API-Football key valid! Plan: {plan} | Used today: {used}/{limit} requests")
            return True
        else:
            print(f"  ❌ API-Football rejected key (HTTP {r.status_code})")
            return False
    except Exception as e:
        print(f"  ❌ Connection error: {e}")
        return False

def test_telegram(token, chat_id):
    try:
        # Test token
        r = requests.get(f"https://api.telegram.org/bot{token}/getMe", timeout=8)
        if r.status_code != 200:
            print(f"  ❌ Telegram token invalid (HTTP {r.status_code})")
            return False
        bot_name = r.json()["result"]["username"]
        print(f"  ✅ Telegram bot valid: @{bot_name}")

        # Test send
        msg = "🤖 Football Prediction Bot connected successfully! You'll receive predictions here."
        r2 = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": msg},
            timeout=8
        )
        if r2.status_code == 200:
            print(f"  ✅ Test message sent to chat {chat_id}!")
            return True
        else:
            err = r2.json().get("description", "Unknown error")
            print(f"  ❌ Could not send to chat {chat_id}: {err}")
            print("     Make sure you started a chat with your bot first (send /start to it)")
            return False
    except Exception as e:
        print(f"  ❌ Connection error: {e}")
        return False

def main():
    print("=" * 55)
    print("  ⚽ Football Prediction Bot — Setup Wizard")
    print("=" * 55)
    print()

    # Check if .env already exists
    if os.path.exists(".env"):
        overwrite = input("  .env already exists. Overwrite? (y/n): ").strip().lower()
        if overwrite != "y":
            print("  Setup cancelled.")
            sys.exit(0)

    print()
    print("  Step 1: API-Football Key")
    print("  ─────────────────────────────────────────────────")
    print("  👉 Get a free key at: https://www.api-football.com")
    print("     (Free tier = 100 requests/day, no credit card needed)")
    print()
    football_key = input("  Paste your API-Football key: ").strip()
    print("  Testing key...")
    api_ok = test_football_api(football_key)

    print()
    print("  Step 2: Telegram Bot Token")
    print("  ─────────────────────────────────────────────────")
    print("  👉 On Telegram: message @BotFather → /newbot")
    print("     Copy the token it gives you (format: 123456:ABCdef...)")
    print()
    telegram_token = input("  Paste your Telegram Bot Token: ").strip()

    print()
    print("  Step 3: Telegram Chat ID")
    print("  ─────────────────────────────────────────────────")
    print("  👉 Message @userinfobot on Telegram to get your Chat ID")
    print("     For a channel: add your bot as admin, then use the channel's @username")
    print("     Chat ID format: a number like 123456789 or -100123456789 for channels")
    print()
    chat_id = input("  Paste your Telegram Chat ID: ").strip()

    print()
    print("  Testing Telegram connection...")
    telegram_ok = test_telegram(telegram_token, chat_id)

    # Write .env
    print()
    env_content = f"""# Football Prediction Bot — Environment Variables
# Generated by setup.py on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}

FOOTBALL_API_KEY={football_key}
TELEGRAM_BOT_TOKEN={telegram_token}
TELEGRAM_CHAT_ID={chat_id}
"""
    with open(".env", "w") as f:
        f.write(env_content)

    print("  ✅ .env file created!")
    print()
    print("=" * 55)

    if api_ok and telegram_ok:
        print("  🎉 All systems go! Run the bot with:")
        print()
        print("     python scheduler.py --now    (run once now)")
        print("     python scheduler.py          (run on schedule)")
    else:
        print("  ⚠️  Setup complete but some checks failed.")
        print("  Fix the issues above, then run:")
        print()
        print("     python setup.py    (re-run setup)")
        print("  or")
        print("     python scheduler.py --now")

    print("=" * 55)

if __name__ == "__main__":
    main()
